---
version: '3'
services:
  registry:
    image: registry
    ports:
    - 5000:5000
    volumes:
    - registry:/var/lib/registry:rw
    environment:
    - REGISTRY_PROXY_REMOTEURL=https://registry-1.docker.io

volumes:
  registry:
