---
version: '3'
services:
  registry:
    image: registry
    ports:
    - 5000:5000
    volumes:
    - registry:/var/lib/registry:rw
    - ./registry-config.yml:/etc/docker/registry/config.yml:ro

volumes:
  registry:
